name: Python Checks

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install flask flake8 bandit

      - name: Lint with flake8
        run: flake8 .

      - name: Security scan with bandit
        run: bandit -r .
